-- Initial schema for Multiservicios Wilson inventory system.
--
-- Generated from the real schema that Hibernate (ddl-auto=update) produces
-- for the current JPA entities (verified via `pg_dump --schema-only`
-- against a clean database), then reordered by FK dependency and given
-- meaningful constraint names instead of Hibernate's auto-generated hashes.
-- From this migration onward, spring.jpa.hibernate.ddl-auto=validate: this
-- file (and the ones that follow it) is the single source of truth for the
-- schema, not Hibernate's automatic DDL generation.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE role (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
        CONSTRAINT role_name_check CHECK (name IN ('ROLE_EMPLOYEE', 'ROLE_ADMIN'))
);

CREATE TABLE users (
    user_id  UUID NOT NULL PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id  INTEGER NOT NULL,
    CONSTRAINT users_username_key UNIQUE (username),
    CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id) REFERENCES role (id)
);

CREATE TABLE product (
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    barcode     VARCHAR(100) NOT NULL,
    description TEXT,
    stock       INTEGER NOT NULL,
    CONSTRAINT product_barcode_key UNIQUE (barcode)
);

CREATE TABLE sales (
    sales_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   UUID NOT NULL,
    customer_name VARCHAR(100),
    date          TIMESTAMP(6) NOT NULL,
    total         NUMERIC(10, 2) NOT NULL,
    CONSTRAINT sales_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES users (user_id)
);

CREATE TABLE sale_detail (
    sale_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_id       BIGINT NOT NULL,
    product_id     BIGINT NOT NULL,
    amount         INTEGER NOT NULL,
    unit_price     NUMERIC(10, 2) NOT NULL,
    CONSTRAINT sale_detail_sales_id_fkey FOREIGN KEY (sales_id) REFERENCES sales (sales_id),
    CONSTRAINT sale_detail_product_id_fkey FOREIGN KEY (product_id) REFERENCES product (product_id)
);

CREATE TABLE stock_alert (
    stock_alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT NOT NULL,
    stock_at_alert INTEGER NOT NULL,
    status         VARCHAR(20) NOT NULL
        CONSTRAINT stock_alert_status_check CHECK (status IN ('PENDIENTE', 'ATENDIDA')),
    created_at     TIMESTAMP(6) NOT NULL,
    attended_at    TIMESTAMP(6),
    CONSTRAINT stock_alert_product_id_fkey FOREIGN KEY (product_id) REFERENCES product (product_id)
);
