-- Notification (RF-06): generic event notifications shown on the
-- dashboard, fed by StockAlert (stock bajo) and, later, by DPI document
-- generation (documento generado). Does not replace stock_alert.

CREATE TABLE notification (
    notification_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                 VARCHAR(30) NOT NULL
        CONSTRAINT notification_type_check CHECK (type IN ('STOCK_BAJO', 'DOCUMENTO_GENERADO')),
    message              VARCHAR(500) NOT NULL,
    related_entity_type  VARCHAR(50),
    related_entity_id    BIGINT,
    read                 BOOLEAN NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP(6) NOT NULL,
    recipient_role       VARCHAR(20)
        CONSTRAINT notification_recipient_role_check CHECK (recipient_role IN ('ROLE_EMPLOYEE', 'ROLE_ADMIN'))
);

CREATE INDEX notification_read_created_at_idx ON notification (read, created_at DESC);
