-- Proveedores: referenciados por Product para la regla de negocio de
-- reposición ("...referenciando al proveedor correspondiente").
CREATE TABLE supplier (
    supplier_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(150) NOT NULL,
    contact_name VARCHAR(150),
    phone        VARCHAR(30)
);
